language: node_js

node_js:
  - "node"
  - 7
  - 6

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change

after_success: 'npm run codecov'

cache:
  yarn: true
  directories:
    - node_modules
